### ISSUE TITLE
Parsing string-value "Yes" has assertion-error

### ISSUE THREAD

**Issue by ErikTrapman** [yaz/yaz_messaging_plugin#2]
E.g.

```yaml
list:
    is_public_visible:
        not.public: No
        yes:
            from: "Yes, from: !date"
            till: "Yes, till !date"
            between: "Yes, between !date_from and !date_till"
            not_scheduled: "Yes"
```
returns
`AssertionError: ['admin.nl.yml', '.list.is_public_visible', True, OrderedDict([('from', 'Yes, from: !date'), ('till', 'Yes, till !date'), ('between', 'Yes, between !date_from and !date_till'), ('not_scheduled', 'Yes')])]`
