### ISSUE TITLE
Keys that appear boolean should not be quoted

### ISSUE THREAD

**Issue by boudewijn-zicht** [yaz/yaz_messaging_plugin#6]
```yaml
hello:
    yes: Positive
    no: Negative
```

is converted into:

```yaml
hello:
    'yes': Positive
    'no': Negative
```

It would be better if the keys stayed unquoted, as is allowed in the yaml 1.2 specs.  A possible solution is described here: https://stackoverflow.com/questions/36463531/pyyaml-automatically-converting-certain-keys-to-boolean-values
